
// generated by scripts/ts_foundry/methods/gen.ts
// Path: scripts/foundry/LedgerOCCManagerSetup.s.sol
import { addOperation } from "../utils/config";
import { set_env_var, foundry_wrapper } from "../foundry";
import { checkArgs } from "../utils/helper";
import { setupDeployJson } from "../utils/setupDeployJson";

// current file name
const method_name = "LedgerOCCManagerSetup";

export function LedgerOCCManagerSetupWithArgv(argv: any) {
    const required_flags = ["env"];
    checkArgs(method_name, argv, required_flags);
    LedgerOCCManagerSetup(argv.env, argv.broadcast, argv.simulate);
}

export function LedgerOCCManagerSetup(env: string, broadcast: boolean, simulate: boolean) {
    

    set_env_var(method_name, "env", env);
    foundry_wrapper(method_name, broadcast, simulate);

}

addOperation(method_name, LedgerOCCManagerSetupWithArgv);
