
// generated by scripts/ts_foundry/methods/gen.ts
// Path: scripts/foundry/LedgerOCCManagerAddNewChain.s.sol
import { addOperation } from "../utils/config";
import { set_env_var, foundry_wrapper } from "../foundry";
import { checkArgs } from "../utils/helper";
import { setupDeployJson } from "../utils/setupDeployJson";

// current file name
const method_name = "LedgerOCCManagerAddNewChain";

export function LedgerOCCManagerAddNewChainWithArgv(argv: any) {
    const required_flags = ["env", "newNetwork"];
    checkArgs(method_name, argv, required_flags);
    LedgerOCCManagerAddNewChain(argv.env, argv.newNetwork, argv.broadcast, argv.simulate);
}

export function LedgerOCCManagerAddNewChain(env: string, newNetwork: string, broadcast: boolean, simulate: boolean) {
    

    set_env_var(method_name, "env", env);
    set_env_var(method_name, "newNetwork", newNetwork);
    foundry_wrapper(method_name, broadcast, simulate);

}

addOperation(method_name, LedgerOCCManagerAddNewChainWithArgv);
