
// generated by scripts/ts_foundry/methods/gen.ts
// Path: scripts/foundry/printAllErrors.s.sol
import { addOperation } from "../utils/config";
import { set_env_var, foundry_wrapper } from "../foundry";
import { checkArgs } from "../utils/helper";
import { printErrorsSig } from "../utils/abiEncode";

// current file name
const method_name = "printAllErrors";

export function printAllErrorsWithArgv(argv: any) {
    const required_flags = ["abi"];
    checkArgs(method_name, argv, required_flags);
    printAllErrors(argv.abi);
}

export function printAllErrors(abi: string) {
    printErrorsSig(abi);
}

addOperation(method_name, printAllErrorsWithArgv);
