
// generated by scripts/ts_foundry/methods/gen.ts
// Path: scripts/foundry/ProxyLedgerSetup.s.sol
import { addOperation } from "../utils/config";
import { set_env_var, foundry_wrapper } from "../foundry";
import { checkArgs } from "../utils/helper";
import { setupDeployJson } from "../utils/setupDeployJson";

// current file name
const method_name = "ProxyLedgerSetup";

export function ProxyLedgerSetupWithArgv(argv: any) {
    const required_flags = ["network", "env"];
    checkArgs(method_name, argv, required_flags);
    ProxyLedgerSetup(argv.network, argv.env, argv.broadcast, argv.simulate);
}

export function ProxyLedgerSetup(network: string, env: string, broadcast: boolean, simulate: boolean) {
    

    set_env_var(method_name, "network", network);
    set_env_var(method_name, "env", env);
    foundry_wrapper(method_name, broadcast, simulate);

}

addOperation(method_name, ProxyLedgerSetupWithArgv);
