
// generated by scripts/ts_foundry/methods/gen.ts
// Path: scripts/foundry/UpgradeLedgerOCCManager.s.sol
import { addOperation } from "../utils/config";
import { set_env_var, foundry_wrapper } from "../foundry";
import { checkArgs } from "../utils/helper";
import { setupDeployJson } from "../utils/setupDeployJson";

// current file name
const method_name = "UpgradeLedgerOCCManager";

export function UpgradeLedgerOCCManagerWithArgv(argv: any) {
    const required_flags = ["env", "broadcast"];
    checkArgs(method_name, argv, required_flags);
    UpgradeLedgerOCCManager(argv.env, argv.broadcast, argv.simulate);
}

export function UpgradeLedgerOCCManager(env: string, broadcast: boolean, simulate: boolean) {
    

    set_env_var(method_name, "env", env);
    set_env_var(method_name, "broadcast", broadcast.toString());
    foundry_wrapper(method_name, broadcast, simulate);

}

addOperation(method_name, UpgradeLedgerOCCManagerWithArgv);
